project:
  type: website
  output-dir: docs

execute:
  freeze: auto
  cache: true

website:
  title: "Personal Blog"
  description: "This is Anes Benmerzoug's personal Blog."
  site-url: https://AnesBenmerzoug.github.io
  repo-url: https://github.com:AnesBenmerzoug/AnesBenmerzoug.github.io
  reader-mode: true
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/index.qmd
        text: Posts
      - icon: github
        href: https://github.com/AnesBenmerzoug

format:
  html:
    theme:
      light: [cosmo, static/styles/fonts.scss]
      dark: [solar, static/styles/custom-dark.scss, static/styles/fonts.scss]
    toc: true
    respect-user-color-scheme: true