baseURL = "https://anesbenmerzoug.github.io"
title = "Anes Benmerzoug"
theme = "hugo-coder"
RelativeURLs=true
CanonifyURLs=true

languageCode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "monokai"

[params]
    author = "Anes Benmerzoug"
    description = "Anes Benmerzoug's personal website"
    keywords = "blog,notes,personal,resume,developer"
    info = "Artifical Intelligence Engineer"
    avatarurl = "images/avatar.jpg"

    dateformat = "January 2, 2006"
    since = 2019

    footercontent = " "

    hideCredits = false
    hideCopyright = false

    rtl = false

    # Use inverted colors
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    math = true

    # Custom CSS
    custom_css = ["css/custom.css"]

    # Custom JS
    custom_js = []

[taxonomies]
  tag = "tags"

[[menu.main]]
    name = "About"
    weight = 1
    url = "about/"

[[menu.main]]
    name = "Resume"
    weight = 4
    url = "resume/"

[[menu.main]]
    name = "Blog"
    weight = 2
    url = "posts/"

[[menu.main]]
    name = "Notes"
    weight = 3
    url = "notes/"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/anesbenmerzoug/"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/anes-benmerzoug/"

