---
date: 2024-09-13
title: "Introduction"
keywords: [
    "Ball and Plate",
    "Control", 
    "System",
]
license: "CC BY"
link-citations: true
---

In this first post of the Control series, we will introduce the system that we want to control as well as the different control
objectives. I am writing this series because I miss working on Control problems.

The aim of this series is to apply as many methods to model, control and observe the chosen system as possible
in order for me to get back some of the knowledge I lost while away from control engineering as well as gain
some new knowledge. 

# Ball and Plate System

The ball and plate (also called ball on plate) system is a benchmark system in control engineering
used to evaluate new control and observation algorithms. It is also a widespread educational system
used in universities to teach students about non-linear control.

It consists of a ball that moves freely along the x and y axes on top of plate that can rotate freely along x and y axes.

::: {#video-ball-plate}

{{ video https://youtu.be/F8R91bAOHSU?si=RlQaEWpiFJpsIQXR }}

Ball and plate balancing with PID controller

:::

In @video-ball-plate, we can see an example of a real ball and plate system whose goal
is to bring the ball back to the center of the plate.

Controlling this type of system is something I tried to do together with my classmates during my first
Master's studies. We did the best we could with our limited budget and resources.

## Modeling

